### ISSUE TITLE
Expose start and end nodes

### ISSUE THREAD

**Issue by wesleytodd** [bmcmahen/selection-range#6]
Right after getting and setting a selection I am finding that I need to get the selection nodes.  It would be much easier to just expose them from here instead of me having to re-get the selection.  If this is something you are interested in I will put together a PR for it.  Let me know!

**Comment by bmcmahen** [comment]
I'm open to the idea. Any idea on what the API would look like? I'd generally like to keep this module as simple and focused as possible.

**Comment by wesleytodd** [comment]
I was thinking it would just be to add the properties from the dom `getRangeAt` method:

```
{
  // ... start, end .....
  commonAncestorContainer: <DOMNode>,
  endContainer: <DOMNode>,
  startContainer: <DOMNode>
}
```

Sound good?

**Comment by bmcmahen** [comment]
Yep, as long as you can pass the result back into the module, I'm good with this. i.e, 

```javascript
var pos = select(el);
select(el, pos);
```

**Comment by wesleytodd** [comment]
Yeah it would just not use those values on the setting cursor part.  Ill put this together sometime this weekend.

**Comment by bmcmahen** [comment]
great, thanks.
