### ISSUE TITLE
Range selection broundry

### ISSUE THREAD

**Issue by wesleytodd** [bmcmahen/selection-range#7]
For example:

```
<div>
  <div id="foo" contenteditable>Some Text</div>
  <p>Other content</p>
</div>
```

```
selection(document.getElementById('foo'), {
  start: 25, // Past content length of 9
  end: 25
});
```

The dom iterator moves right past the end of this node and onto the rest of the document.  It will iterate through all the siblings of the originally passed node before exiting.  Thus the above example sets the cursor in the following `p` tag.

While I understand the behavior, it is counter intuitive.  Seems like there are two better options:

1. Set the cursor at the end of the last text node in the passed element
2. Create some sort of error condition

Since there currently no methods for handeling errors in this code, I would hate to add a `throw` in.  Modules that throw are very annoying to deal with as a consumer.  So it seems to me that option 1 is the best.  

The simple solution would be to check the total length before iterating and limit the start/end to that number.  If you like this I can put together the PR.

**Comment by bmcmahen** [comment]
Yeah, this sounds great. Would gladly accept PR for 1. I agree that it's the best option in this case.
